version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: weekly
      # disable version updates. We only want to have security updates
      open-pull-requests-limit: 0
      commit-message:
          # Prefix all commit messages with "chore: "
          prefix: "chore"
      reviewers:
          - saw-jan
