module.exports = {
    Program: "Program",
    Feature: "Feature",
    Rule: "Rule",
    Background: "BackgroundScenario",
    Scenario: "Scenario",
    ScenarioOutline: "ScenarioOutline",
    Step: "Step",
    StepTable: "StepTable",
    ExampleTable: "ExampleTable",
    Comment: "Comment",
    Tag: "Tag",
    Description: "Description",
    Story: "UserStory",
};
