name: lint-unit

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    lint-unit:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: setup-node
              uses: actions/setup-node@v3
              with:
                  node-version: 14
                  cache: yarn

            - name: yarn-install
              run: yarn install --immutable

            - name: eslint
              run: yarn lint

            - name: commitlint-push
              if: github.event_name == 'push'
              run: yarn commitlint --from HEAD~1 --to HEAD --verbose

            - name: commitlint-pr
              if: github.event_name == 'pull_request'
              run: yarn commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose

            - name: unit-tests
              run: yarn test:unit --silent
