name: lint-unit

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    lint-unit:
        runs-on: ubuntu-latest
        steps:
            - name: cancel-previous-run
              uses: styfle/cancel-workflow-action@0.9.1
              with:
                  all_but_latest: true
                  access_token: ${{ secrets.GITHUB_TOKEN }}

            - name: checkout
              uses: actions/checkout@v3

            - name: setup-node
              uses: actions/setup-node@v3
              with:
                  node-version: 14
                  cache: yarn

            - name: yarn-install
              run: yarn install --immutable

            - name: eslint
              run: yarn lint

            - name: unit-tests
              run: yarn test:unit --coverage false
