name: publish

on:
    release:
        types: [published]

jobs:
    tests:
        uses: ./.github/workflows/ci.yml
    publish:
        needs: [tests]
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: npm-publish
              uses: actions/setup-node@v3
              with:
                  node-version: "14.x"
                  registry-url: "https://registry.npmjs.org"
                  scope: "@gherlint"
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
            - run: yarn
            - run: yarn publish
